export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';

export const REQUEST_FEED = 'REQUEST_FEED';
export const RECEVICE_FEED = 'RECEVICE_FEED';

export const FAIL_NETWORK = 'FAIL_NETWORK';